<script lang="ts">
  import { deserialize, enhance } from "$app/forms";
  import { goto } from "$app/navigation";
  import { navigating } from "$app/state";
  import { page } from "$app/stores";
  import { invalidateAll } from "$app/navigation";
  import { onMount, tick } from "svelte";
  import { Eye, Pencil, Plus, RefreshCw, Trash2, X } from "@lucide/svelte";
  import InvestorMultiSelect from "$lib/components/InvestorMultiSelect.svelte";
  import TableLoading from "$lib/components/TableLoading.svelte";
  import TablePagination from "$lib/components/TablePagination.svelte";
  import TableSearchInput from "$lib/components/TableSearchInput.svelte";
  import TableSortHeader from "$lib/components/TableSortHeader.svelte";
  import SearchSelect from "$lib/components/ui/search-select/search-select.svelte";
  import {
    activeTypeFields,
    batchAttributeEntries,
    batchAttributeLabel,
    batchAttrValue,
    batchTypeKey,
    batchTypeLabel,
  } from "$lib/inventory/stockListDisplay";
  import { resolveBatchProduct } from "$lib/inventory/groupStock";
  import { resolveUniqueBatchNumber } from "$lib/inventory/batchNumber";
  import { parseQty } from "$lib/inventory/fifo";
  import {
    buildCatalogProductName,
    buildProductLabel,
    usesAutoGeneratedProductName,
  } from "$lib/inventory/productLabel";
  import {
    PRODUCT_TYPE_FIELDS,
    normalizeProductTypeName,
  } from "$lib/inventory/parseForm";
  import {
    shouldCollectBatchExpiry,
  } from "$lib/inventory/companyStockFields";
  import type { ProductRecord, StockBatchRecord } from "$lib/inventory/types";
  import { mc } from "$lib/merchant-styles.js";
  import {
    SUBSCRIPTION_BLOCKED_MESSAGE,
    subscriptionBlocksMutations,
  } from "$lib/subscription/client";
  import {
    afterToast,
    showToast,
    toastFromActionResult,
    TOAST_MS,
  } from "$lib/toast";
  import { formatProductTypeLabel } from "$lib/stockLabel";
  import type { PageData } from "./$types";

  type Investor = {
    id: string;
    first_name: string;
    last_name: string;
    phone_number?: string;
  };

  type ProductType = { id: string; name?: string | null };
  type Branch = { id: string; name?: string | null };
  type Product = ProductRecord;
  type StockBatch = StockBatchRecord & { id: string };

  type ReceiveLine = {
    key: string;
    mode: "existing" | "new";
    product_id: string;
    product_type_id: string;
    product_type_name: string;
    name: string;
    default_unit: string;
    attributes: Record<string, string>;
    investors: string[];
    quantity: string;
    purchased_price: string;
    selling_price: string;
    barcode: string;
    qr_code: string;
  };

  let { data }: { data: PageData } = $props();

  let stocks = $state((data.stocks ?? []) as StockBatch[]);
  let totalCount = $state((data as { totalCount: number }).totalCount ?? 0);
  const stocksLoadError = $derived(data.stocksLoadError ?? null);
  const investors = (data.investors ?? []) as Investor[];
  const merchantBranchId = data.merchantBranchId as string | null;
  const companyName = (data.companyName as string | null) ?? "Company";
  const existingBatchNumbers = (data.existingBatchNumbers ?? []) as string[];
  const branches = (data.branches ?? []) as Branch[];

  let searchQuery = $state($page.url.searchParams.get("search") ?? "");
  let typeFilter = $state($page.url.searchParams.get("type") ?? "all");
  let tablePage = $state(Number($page.url.searchParams.get("page")) || 1);
  let tablePageSize = $state(Number($page.url.searchParams.get("pageSize")) || 10);
  let sortColumn = $state<string>($page.url.searchParams.get("sort") ?? "none");
  let sortDirection = $state<"asc" | "desc">(($page.url.searchParams.get("dir") as "asc" | "desc") ?? "asc");
  let searchDebounceTimer: ReturnType<typeof setTimeout> | undefined;
  let suppressPageNav = $state(false);

  let showReceiveModal = $state(false);
  let showEditModal = $state(false);
  let showDeleteModal = $state(false);
  let receivePending = $state(false);
  let editPending = $state(false);
  let deletePending = $state(false);
  let receiveError = $state("");
  let editError = $state("");

  let receiveBatchNumber = $state("");
  let receiveExpiryDate = $state("");
  let receiveLines = $state<ReceiveLine[]>([]);
  let selectedStockProducts = $state(new Map<string, Product>());

  let editingBatch = $state<StockBatch | null>(null);
  let editQuantity = $state("");
  let editBatchNumber = $state("");

  let batchToDelete = $state<StockBatch | null>(null);

  const subscriptionLocked = $derived($subscriptionBlocksMutations);

  const productTypes = (data.productTypes ?? []) as ProductType[];

  $effect(() => {
    stocks = (data.stocks ?? []) as StockBatch[];
    totalCount = (data as { totalCount: number }).totalCount ?? 0;
  });

  function isTypeFilter(v: string | null): v is string {
    if (v == null) return false;
    if (v === "all") return true;
    const names = new Set(
      productTypes.map((p) =>
        String(p.name ?? "")
          .trim()
          .toLowerCase(),
      ),
    );
    for (const n of Object.keys(PRODUCT_TYPE_FIELDS)) names.add(n);
    return names.has(v);
  }

  function branchLabel(branchId: string | null | undefined): string {
    if (!branchId) return "—";
    const b = branches.find((x) => x.id === branchId);
    if (b?.name) return b.name.replaceAll("_", " ").replace(/\b\w/g, (m) => m.toUpperCase());
    return branchId.slice(0, 8) + "…";
  }

  function dash(v: unknown): string {
    if (v === null || v === undefined || v === "") return "—";
    return String(v);
  }

  function attrCellValue(batch: StockBatch, key: string): string {
    return dash(batchAttrValue(batch, key));
  }

  const isSingleTypeFilter = $derived(typeFilter !== "all");
  const activeFields = $derived(activeTypeFields(typeFilter));
  const tableColCount = $derived(8 + (isSingleTypeFilter ? activeFields.length : 1));

  function cycleSort(col: string, e?: Event) {
    e?.stopPropagation();
    if (sortColumn !== col) {
      sortColumn = col;
      sortDirection = "asc";
      return;
    }
    if (sortDirection === "asc") sortDirection = "desc";
    else {
      sortColumn = "none";
      sortDirection = "asc";
    }
  }

  function isSortActive(col: string, dir: "asc" | "desc") {
    return sortColumn === col && sortDirection === dir;
  }

  function navigateWithState() {
    const params = new URLSearchParams();
    if (searchQuery) params.set("search", searchQuery);
    if (typeFilter !== "all") params.set("type", typeFilter);
    if (sortColumn !== "none") {
      params.set("sort", sortColumn);
      params.set("dir", sortDirection);
    }
    if (tablePage > 1) params.set("page", String(tablePage));
    if (tablePageSize !== 10) params.set("pageSize", String(tablePageSize));
    const qs = params.toString();
    goto(qs ? `/stocks?${qs}` : "/stocks", { replaceState: true, keepFocus: true });
  }

  $effect(() => {
    const q = searchQuery;
    const currentSearch = $page.url.searchParams.get("search") ?? "";
    if (q === currentSearch) return;

    clearTimeout(searchDebounceTimer);
    searchDebounceTimer = setTimeout(() => {
      suppressPageNav = true;
      tablePage = 1;
      navigateWithState();
      suppressPageNav = false;
    }, 600);
  });

  $effect(() => {
    if (suppressPageNav) return;
    const tf = typeFilter;
    const sc = sortColumn;
    const sd = sortDirection;
    const pg = tablePage;
    const ps = tablePageSize;

    const urlType = $page.url.searchParams.get("type") ?? "all";
    const urlSort = $page.url.searchParams.get("sort") ?? "none";
    const urlDir = $page.url.searchParams.get("dir") ?? "asc";
    const urlPage = Number($page.url.searchParams.get("page")) || 1;
    const urlPageSize = Number($page.url.searchParams.get("pageSize")) || 10;

    if (tf === urlType && sc === urlSort && sd === urlDir && pg === urlPage && ps === urlPageSize) return;
    navigateWithState();
  });

  function parseMoneyValue(value: number | string | null | undefined): number {
    if (value == null || value === "") return 0;
    if (typeof value === "number") return Number.isFinite(value) ? value : 0;
    const n = Number(String(value).replace(/[^0-9.-]/g, ""));
    return Number.isFinite(n) ? n : 0;
  }

  function formatDate(value: string | null | undefined): string {
    if (!value) return "—";
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return "—";
    return d.toLocaleString(undefined, {
      year: "numeric",
      month: "short",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
    });
  }

  function qtyLabel(batch: StockBatch, product?: ProductRecord | null): string {
    const q = parseQty(batch.quantity);
    const unit = String(product?.default_unit ?? "").trim();
    return unit ? `${q.toLocaleString()} ${unit}` : q.toLocaleString();
  }

  function typeDisplay(name: string | null | undefined): string {
    return formatProductTypeLabel(name);
  }

  function attributeLabel(key: string): string {
    return batchAttributeLabel(key);
  }

  function lineTypeKey(line: ReceiveLine): string | null {
    if (line.mode === "new") {
      const name = line.product_type_name.trim();
      return name ? normalizeProductTypeName(name) : null;
    }
    if (!line.product_id) return null;
    const product = selectedStockProducts.get(line.product_id);
    const typeName = product?.product_type?.name;
    return typeName ? normalizeProductTypeName(String(typeName)) : null;
  }

  const showReceiveExpiry = $derived.by(() => {
    const keys = receiveLines
      .map(lineTypeKey)
      .filter((k): k is string => k != null && k !== "");
    return shouldCollectBatchExpiry(keys);
  });

  $effect(() => {
    if (!showReceiveExpiry) receiveExpiryDate = "";
  });

  function typeFields(typeName: string): string[] {
    return PRODUCT_TYPE_FIELDS[normalizeProductTypeName(typeName)] ?? [];
  }

  function lineUsesAutoName(line: ReceiveLine): boolean {
    return usesAutoGeneratedProductName(line.product_type_name);
  }

  function lineGeneratedName(line: ReceiveLine): string {
    return buildCatalogProductName(line.product_type_name, line.attributes);
  }

  function lineGeneratedDisplayLabel(line: ReceiveLine): string {
    const name = lineGeneratedName(line);
    if (!name || name === "Stock") return "";
    return buildProductLabel({
      id: "",
      name,
      default_unit: line.default_unit || "—",
      attributes: line.attributes,
      product_type: { id: "", name: line.product_type_name },
    });
  }

  function newReceiveLine(): ReceiveLine {
    return {
      key: crypto.randomUUID(),
      mode: "existing",
      product_id: "",
      product_type_id: "",
      product_type_name: "",
      name: "",
      default_unit: "Pieces",
      attributes: {},
      investors: [],
      quantity: "",
      purchased_price: "",
      selling_price: "",
      barcode: "",
      qr_code: "",
    };
  }

  function pickUniqueBatchNumber(preferred: string | null = null): string {
    return resolveUniqueBatchNumber(companyName, existingBatchNumbers, preferred);
  }

  function openReceiveModal() {
    if (subscriptionLocked) return;
    receiveError = "";
    receiveBatchNumber = pickUniqueBatchNumber();
    receiveExpiryDate = "";
    receiveLines = [newReceiveLine()];
    showReceiveModal = true;
  }

  function regenerateBatchNumber() {
    receiveBatchNumber = pickUniqueBatchNumber();
  }

  function closeReceiveModal() {
    if (receivePending) return;
    showReceiveModal = false;
    receiveLines = [];
    receiveError = "";
  }

  function addReceiveLine() {
    if (receiveLines.length >= 15) return;
    receiveLines = [...receiveLines, newReceiveLine()];
  }

  function removeReceiveLine(key: string) {
    if (receiveLines.length <= 1) return;
    receiveLines = receiveLines.filter((l) => l.key !== key);
  }

  function setLineMode(key: string, mode: "existing" | "new") {
    receiveLines = receiveLines.map((line) => {
      if (line.key !== key) return line;
      if (mode === "existing") {
        return {
          ...line,
          mode,
          product_type_id: "",
          product_type_name: "",
          name: "",
          attributes: {},
          investors: [],
          barcode: "",
          qr_code: "",
        };
      }
      return {
        ...line,
        mode,
        product_id: "",
      };
    });
  }

  function onLineProductTypeChange(key: string, productTypeId: string) {
    const found = productTypes.find((pt) => pt.id === productTypeId);
    const product_type_name = normalizeProductTypeName(String(found?.name ?? ""));
    const attributes: Record<string, string> = {};
    for (const field of typeFields(product_type_name)) {
      attributes[field] = "";
    }
    receiveLines = receiveLines.map((line) =>
      line.key === key
        ? { ...line, product_type_id: productTypeId, product_type_name, attributes }
        : line,
    );
  }

  function buildReceiveLinesPayload(): string {
    const lines = receiveLines.map((line) => {
      const quantity = Number(line.quantity);
      const purchased_price = Number(line.purchased_price);
      const selling_price = Number(line.selling_price);
      if (line.mode === "existing") {
        return {
          mode: "existing" as const,
          product_id: line.product_id,
          quantity,
          purchased_price,
          selling_price,
        };
      }
      return {
        mode: "new" as const,
        product_type_id: line.product_type_id,
        product_type_name: line.product_type_name,
        name: lineUsesAutoName(line)
          ? lineGeneratedName(line)
          : line.name.trim(),
        default_unit: line.default_unit.trim(),
        attributes: line.attributes,
        investors: line.investors,
        factor: Number(line.attributes.factor) || 1,
        barcode: line.barcode.trim() || null,
        qr_code: line.qr_code.trim() || null,
        quantity,
        purchased_price,
        selling_price,
      };
    });
    return JSON.stringify(lines);
  }

  function validateReceiveForm(): string | null {
    if (!merchantBranchId) return "Branch could not be resolved";
    for (const line of receiveLines) {
      const qty = Number(line.quantity);
      const purchase = Number(line.purchased_price);
      const sell = Number(line.selling_price);
      if (!Number.isFinite(qty) || qty <= 0) return "Each line needs quantity greater than zero";
      if (!Number.isFinite(purchase) || purchase < 0) return "Each line needs a valid purchase price";
      if (!Number.isFinite(sell) || sell <= 0) return "Each line needs a valid selling price";
      if (line.mode === "existing") {
        if (!line.product_id) return "Select a product for each line";
      } else {
        if (!line.product_type_id) return "Product type is required for new products";
        if (!line.default_unit.trim()) return "Unit is required for new products";
        if (line.investors.length === 0) return "Select at least one investor for new products";
        if (lineUsesAutoName(line)) {
          const built = lineGeneratedName(line);
          if (!built || built === "Stock") {
            return "Enter model number, country, or other attributes so the product name can be generated";
          }
        } else if (!line.name.trim()) {
          return "Product name is required for new products";
        }
      }
    }
    return null;
  }

  function openEditModal(batch: StockBatch, e?: Event) {
    if (subscriptionLocked) return;
    e?.stopPropagation();
    editingBatch = batch;
    editQuantity = String(parseQty(batch.quantity));
    editBatchNumber = String(batch.batch_number ?? "");
    editError = "";
    showEditModal = true;
  }

  function closeEditModal() {
    if (editPending) return;
    showEditModal = false;
    editingBatch = null;
    editError = "";
  }

  function openDeleteModal(batch: StockBatch, e?: Event) {
    if (subscriptionLocked) return;
    e?.stopPropagation();
    if (parseQty(batch.quantity) !== 0) return;
    batchToDelete = batch;
    showDeleteModal = true;
  }

  function closeDeleteModal(force = false) {
    if (!force && deletePending) return;
    showDeleteModal = false;
    batchToDelete = null;
  }

  async function confirmDelete() {
    if (!batchToDelete || deletePending) return;
    deletePending = true;
    try {
      const formData = new FormData();
      formData.append("stockId", batchToDelete.id);
      const response = await fetch("?/deleteStock", { method: "POST", body: formData });
      const result = deserialize(await response.text());
      const t = toastFromActionResult(result);
      if (t) showToast(t.message, t.variant);
      const payload =
        result.type === "success" && "data" in result
          ? (result.data as { success?: boolean } | undefined)
          : undefined;
      if (result.type === "success" && payload?.success) {
        closeDeleteModal(true);
        afterToast(TOAST_MS, () => void invalidateAll());
      }
    } catch {
      showToast("Failed to delete batch. Please try again.", "error");
    } finally {
      deletePending = false;
    }
  }

  function canDelete(batch: StockBatch): boolean {
    return parseQty(batch.quantity) === 0;
  }
</script>

<section class={mc.pageHeader}>
  <div>
    <h1 class={mc.pageTitle}>Stocks</h1>
    <p class={mc.pageSubtitle}>
      Inventory batches. Receive stock or edit individual batches.
    </p>
  </div>
  <button
    type="button"
    class={mc.primaryBtn}
    onclick={openReceiveModal}
    disabled={subscriptionLocked}
    title={subscriptionLocked ? SUBSCRIPTION_BLOCKED_MESSAGE : undefined}
  >
    Receive stock
  </button>
</section>

{#if stocksLoadError}
  <div class="mx-auto mb-4 max-w-5xl rounded-lg border border-red-300 bg-red-50 px-4 py-3 text-sm text-red-900 dark:border-red-800 dark:bg-red-950/40 dark:text-red-100" role="alert">
    Could not load stock from the server: {stocksLoadError}
  </div>
{/if}

<section class={mc.tableSection}>
  <div class={mc.tableToolbar}>
    <TableSearchInput
      bind:value={searchQuery}
      placeholder="Search by product, type, attributes, batch…"
      ariaLabel="Search stocks"
      class="flex-1"
    />
    <div class={mc.tableToolbarFilter}>
      <span class={mc.tableToolbarFilterLabel}>Type</span>
      <select class={mc.filterSelectCompact} bind:value={typeFilter} aria-label="Filter by type">
        <option value="all">All</option>
        {#each productTypes as pt}
          {#if pt.name}
            <option value={String(pt.name).trim().toLowerCase()}>
              {typeDisplay(pt.name)}
            </option>
          {/if}
        {/each}
      </select>
    </div>
  </div>

  <div class="overflow-x-auto">
    <table class={mc.table}>
      <thead>
        <tr>
          <th class={mc.colNumHead}>#</th>
          <th class={mc.th} aria-sort={sortColumn === "type" ? (sortDirection === "asc" ? "ascending" : "descending") : "none"}>
            <TableSortHeader label="Type" onclick={() => cycleSort("type")} ascActive={isSortActive("type", "asc")} descActive={isSortActive("type", "desc")} />
          </th>
          <th class={mc.th} aria-sort={sortColumn === "batch" ? (sortDirection === "asc" ? "ascending" : "descending") : "none"}>
            <TableSortHeader label="Batch" onclick={() => cycleSort("batch")} ascActive={isSortActive("batch", "asc")} descActive={isSortActive("batch", "desc")} />
          </th>
          <th class={mc.th} aria-sort={sortColumn === "branch" ? (sortDirection === "asc" ? "ascending" : "descending") : "none"}>
            <TableSortHeader label="Branch" onclick={() => cycleSort("branch")} ascActive={isSortActive("branch", "asc")} descActive={isSortActive("branch", "desc")} />
          </th>
          <th class={mc.th} aria-sort={sortColumn === "origin" ? (sortDirection === "asc" ? "ascending" : "descending") : "none"}>
            <TableSortHeader label="Origin" onclick={() => cycleSort("origin")} ascActive={isSortActive("origin", "asc")} descActive={isSortActive("origin", "desc")} />
          </th>
          {#if isSingleTypeFilter}
            {#each activeFields as field}
              <th class={mc.th} aria-sort={sortColumn === field ? (sortDirection === "asc" ? "ascending" : "descending") : "none"}>
                <TableSortHeader label={attributeLabel(field)} onclick={() => cycleSort(field)} ascActive={isSortActive(field, "asc")} descActive={isSortActive(field, "desc")} />
              </th>
            {/each}
          {:else}
            <th class={mc.th}>Attributes</th>
          {/if}
          <th class={mc.thCenter} aria-sort={sortColumn === "quantity" ? (sortDirection === "asc" ? "ascending" : "descending") : "none"}>
            <TableSortHeader label="Qty" align="center" onclick={() => cycleSort("quantity")} ascActive={isSortActive("quantity", "asc")} descActive={isSortActive("quantity", "desc")} />
          </th>
          <th class={mc.th} aria-sort={sortColumn === "received" ? (sortDirection === "asc" ? "ascending" : "descending") : "none"}>
            <TableSortHeader label="Received" onclick={() => cycleSort("received")} ascActive={isSortActive("received", "asc")} descActive={isSortActive("received", "desc")} />
          </th>
          <th class={mc.thCenter}>Actions</th>
        </tr>
      </thead>
      <tbody>
        {#if navigating.to}
          <TableLoading rows={1} cols={tableColCount} />
        {:else}
          {#each stocks as batch, i (batch.id)}
            {@const product = resolveBatchProduct(batch)}
            <tr>
              <td class={mc.colNum}>{(tablePage - 1) * tablePageSize + i + 1}</td>
              <td class={mc.td}>{batchTypeLabel(batch)}</td>
              <td class={mc.td}>
                <span class="font-medium text-gray-900 dark:text-gray-100">
                  {batch.batch_number?.trim() || "—"}
                </span>
                {#if batch.product_id}
                  <span class="ml-1 text-xs text-emerald-600 dark:text-emerald-400">linked</span>
                {/if}
              </td>
              <td class={mc.td}>{branchLabel(batch.branch)}</td>
              <td class={mc.td}>{batch.origin ? branchLabel(batch.origin) : "—"}</td>
              {#if isSingleTypeFilter}
                {#each activeFields as field}
                  <td class={mc.td}>{attrCellValue(batch, field)}</td>
                {/each}
              {:else}
                <td class={mc.td}>
                  {#if batchAttributeEntries(batch).length > 0}
                    <div class="flex flex-col gap-0.5 text-sm">
                      {#each batchAttributeEntries(batch) as [k, v]}
                        <div class="attr-row">
                          <span class="attr-key">{attributeLabel(k)}</span>
                          <span class="attr-sep">:</span>
                          <span class="attr-val">{v}</span>
                        </div>
                      {/each}
                    </div>
                  {:else}
                    —
                  {/if}
                </td>
              {/if}
              <td class={mc.tdRight}>{qtyLabel(batch, product)}</td>
              <td class={mc.td}>{formatDate(batch.created_at)}</td>
              <td class={mc.tdCenter}>
                <div class="flex items-center justify-center gap-1.5">
                  <a
                    href="/stocks/{batch.id}"
                    class={mc.actionBtn}
                    aria-label="View stock"
                    title="View stock details"
                  >
                    <Eye size={14} strokeWidth={2} />
                  </a>
                  <button
                    type="button"
                    class={mc.actionBtn}
                    onclick={(e) => openEditModal(batch, e)}
                    disabled={subscriptionLocked}
                    aria-label="Edit batch"
                    title={subscriptionLocked ? SUBSCRIPTION_BLOCKED_MESSAGE : "Edit batch"}
                  >
                    <Pencil size={14} strokeWidth={2} />
                  </button>
                  <button
                    type="button"
                    class={mc.actionBtnDanger}
                    onclick={(e) => openDeleteModal(batch, e)}
                    disabled={subscriptionLocked || !canDelete(batch)}
                    aria-label="Delete batch"
                    title={!canDelete(batch)
                      ? "Only zero-quantity batches can be deleted"
                      : subscriptionLocked
                        ? SUBSCRIPTION_BLOCKED_MESSAGE
                        : "Delete batch"}
                  >
                    <Trash2 size={14} strokeWidth={2} />
                  </button>
                </div>
              </td>
            </tr>
          {/each}
          {#if stocks.length === 0}
            <tr>
              <td colspan={tableColCount} class={mc.emptyCell}>
                {#if totalCount === 0}
                  {#if stocksLoadError}
                    Stock could not be loaded — see the error above.
                  {:else if typeFilter !== "all"}
                    No batches match this type filter.
                  {:else}
                    No stock batches yet. Use Receive stock to add inventory.
                  {/if}
                {:else if typeFilter !== "all"}
                  No batches match this type filter.
                {:else}
                  No batches match your search.
                {/if}
              </td>
            </tr>
          {/if}
        {/if}
      </tbody>
    </table>
  </div>

  <TablePagination
    bind:page={tablePage}
    bind:pageSize={tablePageSize}
    total={totalCount}
    resetKey={totalCount}
  />
</section>

{#if showReceiveModal}
  <div
    class="modal-overlay"
    role="button"
    tabindex="0"
    onclick={() => !receivePending && closeReceiveModal()}
    onkeydown={(e) =>
      !receivePending && (e.key === "Enter" || e.key === " ") && closeReceiveModal()}
  ></div>
  <dialog
    open
    class="modal modal-wide"
    onclick={(e) => e.stopPropagation()}
    oncancel={(e) => receivePending && e.preventDefault()}
  >
    <header>
      <h2>Receive stock</h2>
      <button
        type="button"
        class="icon-btn"
        aria-label="Close"
        disabled={receivePending}
        onclick={closeReceiveModal}
      >
        <X size={18} />
      </button>
    </header>

    <form
      class="form"
      data-receive-stock-scroll
      method="POST"
      action="?/receiveStock"
      use:enhance={({ cancel }) => {
        const err = validateReceiveForm();
        if (err) {
          receiveError = err;
          cancel();
          return;
        }
        receiveError = "";
        receivePending = true;
        return async ({ update, result }) => {
          try {
            await update();
          } finally {
            receivePending = false;
          }
          const t = toastFromActionResult(result);
          if (t) showToast(t.message, t.variant);
          const ok =
            result.type === "success" &&
            result.data &&
            typeof result.data === "object" &&
            "success" in result.data &&
            (result.data as { success?: boolean }).success === true;
          if (ok) {
            closeReceiveModal();
            afterToast(TOAST_MS, () => void invalidateAll());
          } else if (t?.variant === "error") {
            receiveError = t.message;
          }
        };
      }}
    >
      {#if receiveError}
        <div class="form-alert error" role="alert">{receiveError}</div>
      {/if}

      <input type="hidden" name="branch" value={merchantBranchId ?? ""} />
      <input type="hidden" name="lines" value={buildReceiveLinesPayload()} />

      <fieldset class="receive-form-fields" disabled={receivePending}>
        <div class="receive-meta-grid">
          <label class="field">
            <span>Batch number</span>
            <div class="batch-number-row">
              <input
                type="text"
                name="batch_number"
                class="batch-readonly"
                bind:value={receiveBatchNumber}
                readonly
                autocomplete="off"
              />
              <button
                type="button"
                class="batch-regen"
                onclick={regenerateBatchNumber}
                disabled={receivePending}
                title="Generate new batch number"
                aria-label="Generate new batch number"
              >
                <RefreshCw size={15} strokeWidth={2} />
              </button>
            </div>
            <p class="field-hint">Auto-generated from your company name</p>
          </label>
          {#if showReceiveExpiry}
            <label class="field">
              <span>Expiry date <span class="optional">(optional)</span></span>
              <input type="date" name="expiry_date" bind:value={receiveExpiryDate} />
            </label>
          {/if}
        </div>

        <div class="lines-header">
          <div>
            <h3>Line items</h3>
            <p class="lines-sub">Add one or more products to this batch receipt.</p>
          </div>
          <button
            type="button"
            class="add-line-btn"
            onclick={addReceiveLine}
            disabled={receiveLines.length >= 15}
          >
            <Plus size={14} strokeWidth={2.5} />
            Add line
          </button>
        </div>

        {#each receiveLines as line, idx (line.key)}
          <div class="receive-line-card">
            <div class="line-card-head">
              <span class="line-badge">Line {idx + 1}</span>
              <div class="mode-segment" role="tablist" aria-label="Product source">
                <button
                  type="button"
                  role="tab"
                  aria-selected={line.mode === "existing"}
                  class:active={line.mode === "existing"}
                  onclick={() => setLineMode(line.key, "existing")}
                >
                  Existing product
                </button>
                <button
                  type="button"
                  role="tab"
                  aria-selected={line.mode === "new"}
                  class:active={line.mode === "new"}
                  onclick={() => setLineMode(line.key, "new")}
                >
                  New product
                </button>
              </div>
              {#if receiveLines.length > 1}
                <button
                  type="button"
                  class="remove-line-btn"
                  onclick={() => removeReceiveLine(line.key)}
                  aria-label="Remove line"
                  title="Remove line"
                >
                  <X size={15} strokeWidth={2} />
                </button>
              {/if}
            </div>

            {#if line.mode === "existing"}
              <div class="line-form-grid">
                <div class="field span-2">
                  <span>Product</span>
                  <SearchSelect
                    value={line.product_id}
                    onselect={(productId: string, product: any) => {
                      if (product) {
                        selectedStockProducts = new Map(selectedStockProducts).set(productId, product as Product);
                      }
                      receiveLines = receiveLines.map((l) =>
                        l.key === line.key ? { ...l, product_id: productId } : l,
                      );
                    }}
                    companyId={data.companyId ?? ''}
                    placeholder="Search and select a product"
                    disabled={receivePending}
                    itemLabel={(p: any) => {
                      const label = buildProductLabel(p);
                      const unit = p.default_unit?.trim();
                      return unit ? `${label} · ${unit}` : label;
                    }}
                  />
                </div>
              </div>
            {:else}
              <div class="line-form-grid">
                <label class="field">
                  <span>Product type</span>
                  <select
                    class="merchant-filter-select"
                    value={line.product_type_id}
                    required={line.mode === "new"}
                    onchange={(e) =>
                      onLineProductTypeChange(line.key, (e.currentTarget as HTMLSelectElement).value)}
                  >
                    <option value="">Select type</option>
                    {#each productTypes as pt (pt.id)}
                      <option value={pt.id}>{typeDisplay(pt.name)}</option>
                    {/each}
                  </select>
                </label>
                <label class="field">
                  <span>Unit</span>
                  <input
                    type="text"
                    bind:value={line.default_unit}
                    required={line.mode === "new"}
                    maxlength="64"
                    autocomplete="off"
                  />
                </label>
                {#each typeFields(line.product_type_name) as field}
                  <label class="field">
                    <span>{attributeLabel(field)}</span>
                    <input
                      type="text"
                      bind:value={line.attributes[field]}
                      autocomplete="off"
                    />
                  </label>
                {/each}
                {#if lineUsesAutoName(line)}
                  <div class="field span-2 generated-name-field">
                    <span>Product name</span>
                    <p class="generated-name-preview" aria-live="polite">
                      {#if lineGeneratedDisplayLabel(line)}
                        {lineGeneratedDisplayLabel(line)}
                      {:else}
                        <span class="generated-name-placeholder"
                          >Fill in attributes above — name is built automatically.</span
                        >
                      {/if}
                    </p>
                  </div>
                {:else}
                  <label class="field span-2">
                    <span>Name</span>
                    <input
                      type="text"
                      bind:value={line.name}
                      required={line.mode === "new"}
                      placeholder="Product name"
                      autocomplete="off"
                    />
                  </label>
                {/if}
                <div class="field span-2">
                  <span>Investors</span>
                  <InvestorMultiSelect
                    bind:selectedIds={line.investors}
                    {investors}
                    disabled={receivePending}
                  />
                </div>
                <label class="field">
                  <span>Barcode <span class="optional">(optional)</span></span>
                  <input
                    type="text"
                    bind:value={line.barcode}
                    autocomplete="off"
                    placeholder="Scan or enter barcode"
                  />
                </label>
                <label class="field">
                  <span>QR code <span class="optional">(optional)</span></span>
                  <input
                    type="text"
                    bind:value={line.qr_code}
                    autocomplete="off"
                    placeholder="Scan or enter QR value"
                  />
                </label>
              </div>
            {/if}

            <div class="line-form-grid prices-grid">
              <label class="field">
                <span>Quantity</span>
                <input
                  type="number"
                  min="0.001"
                  step="any"
                  bind:value={line.quantity}
                  required
                  placeholder="0"
                />
              </label>
              <label class="field">
                <span>Purchase price</span>
                <input
                  type="number"
                  min="0"
                  step="any"
                  bind:value={line.purchased_price}
                  required
                  placeholder="0"
                />
              </label>
              <label class="field">
                <span>Selling price</span>
                <input
                  type="number"
                  min="0.001"
                  step="any"
                  bind:value={line.selling_price}
                  required
                  placeholder="0"
                />
              </label>
            </div>
          </div>
        {/each}
      </fieldset>

      <footer>
        <button type="button" class="ghost" onclick={closeReceiveModal} disabled={receivePending}>
          Cancel
        </button>
        <button type="submit" class="primary" disabled={receivePending}>
          {receivePending ? "Receiving…" : "Receive stock"}
        </button>
      </footer>
    </form>
  </dialog>
{/if}

{#if showEditModal && editingBatch}
  <div
    class="modal-overlay"
    role="button"
    tabindex="0"
    onclick={() => !editPending && closeEditModal()}
    onkeydown={(e) =>
      !editPending && (e.key === "Enter" || e.key === " ") && closeEditModal()}
  ></div>
  <dialog
    open
    class="modal"
    onclick={(e) => e.stopPropagation()}
    oncancel={(e) => editPending && e.preventDefault()}
  >
    <header>
      <h2>Edit batch</h2>
      <button
        type="button"
        class="icon-btn"
        aria-label="Close"
        disabled={editPending}
        onclick={closeEditModal}
      >
        <X size={18} />
      </button>
    </header>

    <form
      class="form"
      method="POST"
      action="?/updateBatch"
      use:enhance={() => {
        editPending = true;
        return async ({ update, result }) => {
          try {
            await update();
          } finally {
            editPending = false;
          }
          const t = toastFromActionResult(result);
          if (t) showToast(t.message, t.variant);
          const ok =
            result.type === "success" &&
            result.data &&
            typeof result.data === "object" &&
            "success" in result.data &&
            (result.data as { success?: boolean }).success === true;
          if (ok) {
            closeEditModal();
            afterToast(TOAST_MS, () => void invalidateAll());
          } else if (t?.variant === "error") {
            editError = t.message;
          }
        };
      }}
    >
      {#if editError}
        <div class="form-alert error" role="alert">{editError}</div>
      {/if}

      <input type="hidden" name="id"  value={editingBatch.id}  />

      <fieldset class="form-fields" disabled={editPending}>
        <div class="edit-grid">
          <label >
            <span>Batch number</span>
            <input type="text" name="batch_number" bind:value={editBatchNumber} autocomplete="off" disabled  />
          </label>
          <label>
            <span>Quantity</span>
            <input
              type="number"
              name="quantity"
              min="0"
              step="any"
              bind:value={editQuantity}
              required
            />
          </label>
        </div>
      </fieldset>

      <footer>
        <button type="button" class={mc.tableBtn} onclick={closeEditModal} disabled={editPending}>
          Cancel
        </button>
        <button type="submit" class={mc.primaryBtn} disabled={editPending}>
          {editPending ? "Saving…" : "Save changes"}
        </button>
      </footer>
    </form>
  </dialog>
{/if}

{#if showDeleteModal && batchToDelete}
  <div
    class="modal-overlay"
    role="button"
    tabindex="0"
    onclick={() => !deletePending && closeDeleteModal()}
    onkeydown={(e) =>
      !deletePending && (e.key === "Enter" || e.key === " ") && closeDeleteModal()}
  ></div>
  <dialog
    open
    class="modal modal-sm"
    onclick={(e) => e.stopPropagation()}
    oncancel={(e) => deletePending && e.preventDefault()}
  >
    <header>
      <h2>Delete batch</h2>
      <button
        type="button"
        class="icon-btn"
        aria-label="Close"
        disabled={deletePending}
        onclick={() => closeDeleteModal()}
      >
        <X size={18} />
      </button>
    </header>
    <div class="modal-body">
      <p>Delete this zero-quantity batch? This cannot be undone.</p>
      <p class="detail">
        Batch {batchToDelete.batch_number?.trim() || "—"}
        {#if batchToDelete.product}
          · {buildProductLabel(batchToDelete.product)}
        {/if}
      </p>
    </div>
    <footer>
      <button type="button" class={mc.tableBtn} onclick={() => closeDeleteModal()} disabled={deletePending}>
        Cancel
      </button>
      <button type="button" class="danger-btn" onclick={confirmDelete} disabled={deletePending}>
        {deletePending ? "Deleting…" : "Delete"}
      </button>
    </footer>
  </dialog>
{/if}

<style>
  .modal-overlay {
    position: fixed;
    inset: 0;
    background: rgb(2 6 23 / 0.55);
    backdrop-filter: blur(2px);
    z-index: 30;
  }

  .modal {
    position: fixed;
    inset: 0;
    margin: auto;
    max-width: 560px;
    width: calc(100% - 2rem);
    max-height: min(92vh, 880px);
    display: flex;
    flex-direction: column;
    background: white;
    border: 1px solid #e6eaed;
    border-radius: 0.75rem;
    padding: 0;
    z-index: 40;
    overflow: hidden;
    color: #1a1a1a;
  }

  :global(.dark) .modal {
    background: #0f172a;
    border-color: rgb(255 255 255 / 0.1);
    color: #e5e7eb;
  }

  .modal-wide {
    max-width: 760px;
  }

  .modal-sm {
    max-width: 440px;
  }

  .modal header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem 1.25rem;
    border-bottom: 1px solid #e6eaed;
  }

  :global(.dark) .modal header {
    border-bottom-color: rgb(255 255 255 / 0.1);
  }

  .modal h2 {
    margin: 0;
    font-size: 1.1rem;
    font-weight: 600;
  }

  .icon-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border: none;
    background: transparent;
    color: #64748b;
    cursor: pointer;
    padding: 0.25rem;
    border-radius: 0.375rem;
  }

  .icon-btn:hover {
    background: #f1f5f9;
    color: #334155;
  }

  :global(.dark) .icon-btn:hover {
    background: rgb(255 255 255 / 0.08);
    color: #e2e8f0;
  }

  .form {
    display: flex;
    flex-direction: column;
    flex: 1;
    min-height: 0;
    overflow-y: auto;
  }

  .form-fields,
  .receive-form-fields {
    border: none;
    margin: 0;
    padding: 1rem 1.25rem;
    min-width: 0;
  }

  .receive-meta-grid,
  .line-form-grid,
  .edit-grid {
    display: grid;
    gap: 0.875rem;
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .line-form-grid .span-2,
  .receive-meta-grid .span-2 {
    grid-column: span 2;
  }

  .prices-grid {
    margin-top: 0.875rem;
    grid-template-columns: repeat(3, minmax(0, 1fr));
  }

  .field {
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
    min-width: 0;
  }

  .field > span {
    font-size: 0.8125rem;
    font-weight: 500;
    color: #64748b;
  }

  :global(.dark) .field > span {
    color: #94a3b8;
  }

  .optional {
    font-weight: 400;
    opacity: 0.75;
  }

  .field-hint {
    margin: 0.15rem 0 0;
    font-size: 0.75rem;
    color: #94a3b8;
  }

  .batch-number-row {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .batch-readonly {
    flex: 1;
    min-height: 38px;
    font-weight: 600;
    letter-spacing: 0.02em;
    color: #1a1a1a;
    background: #f8fafc;
    cursor: default;
  }

  :global(.dark) .batch-readonly {
    color: #f1f5f9;
    background: rgb(255 255 255 / 0.05);
  }

  .batch-regen {
    display: inline-flex;
    width: 34px;
    height: 34px;
    flex-shrink: 0;
    align-items: center;
    justify-content: center;
    border: 1px solid #e6eaed;
    border-radius: 0.5rem;
    background: white;
    color: #64748b;
    cursor: pointer;
    transition: background 0.15s, color 0.15s, border-color 0.15s;
  }

  .batch-regen:hover:not(:disabled) {
    background: #f8fafc;
    color: #4da0e6;
    border-color: #4da0e6;
  }

  :global(.dark) .batch-regen {
    border-color: rgb(255 255 255 / 0.12);
    background: #111827;
    color: #94a3b8;
  }

  .lines-header {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 1rem;
    margin: 1.25rem 0 0.875rem;
    padding-top: 0.25rem;
    border-top: 1px solid #eef2f6;
  }

  :global(.dark) .lines-header {
    border-top-color: rgb(255 255 255 / 0.08);
  }

  .lines-header h3 {
    margin: 0;
    font-size: 0.9375rem;
    font-weight: 600;
    color: #1a1a1a;
  }

  :global(.dark) .lines-header h3 {
    color: #f1f5f9;
  }

  .lines-sub {
    margin: 0.2rem 0 0;
    font-size: 0.8125rem;
    color: #94a3b8;
  }

  .add-line-btn {
    display: inline-flex;
    align-items: center;
    gap: 0.35rem;
    height: 30px;
    padding: 0 0.75rem;
    border: 1px solid #e6eaed;
    border-radius: 5px;
    background: white;
    font-size: 0.8125rem;
    font-weight: 600;
    color: #374151;
    cursor: pointer;
    white-space: nowrap;
  }

  .add-line-btn:hover:not(:disabled) {
    background: #f8fafc;
    border-color: #4da0e6;
    color: #4da0e6;
  }

  :global(.dark) .add-line-btn {
    background: #111827;
    border-color: rgb(255 255 255 / 0.12);
    color: #e2e8f0;
  }

  .receive-line-card {
    border: 1px solid #e6eaed;
    border-radius: 0.625rem;
    padding: 1rem;
    margin-bottom: 0.875rem;
    background: linear-gradient(180deg, #fcfcfd 0%, #f8fafc 100%);
    box-shadow: 0 1px 2px rgb(15 23 42 / 0.04);
  }

  :global(.dark) .receive-line-card {
    border-color: rgb(255 255 255 / 0.1);
    background: linear-gradient(180deg, rgb(255 255 255 / 0.04) 0%, rgb(255 255 255 / 0.02) 100%);
    box-shadow: none;
  }

  .line-card-head {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    margin-bottom: 0.875rem;
    flex-wrap: wrap;
  }

  .line-badge {
    display: inline-flex;
    align-items: center;
    height: 1.5rem;
    padding: 0 0.5rem;
    border-radius: 999px;
    background: #eef6fd;
    color: #2563eb;
    font-size: 0.75rem;
    font-weight: 700;
    letter-spacing: 0.01em;
  }

  :global(.dark) .line-badge {
    background: rgb(77 160 230 / 0.15);
    color: #93c5fd;
  }

  .mode-segment {
    display: inline-flex;
    padding: 0.15rem;
    border: 1px solid #e6eaed;
    border-radius: 999px;
    background: white;
    gap: 0.15rem;
  }

  :global(.dark) .mode-segment {
    border-color: rgb(255 255 255 / 0.12);
    background: #0f172a;
  }

  .mode-segment button {
    border: none;
    background: transparent;
    padding: 0.35rem 0.75rem;
    border-radius: 999px;
    font-size: 0.75rem;
    font-weight: 600;
    cursor: pointer;
    color: #64748b;
    transition: background 0.15s, color 0.15s;
  }

  .mode-segment button.active {
    background: #4da0e6;
    color: white;
    box-shadow: 0 1px 2px rgb(77 160 230 / 0.35);
  }

  .remove-line-btn {
    margin-left: auto;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 30px;
    height: 30px;
    border: none;
    border-radius: 0.375rem;
    background: transparent;
    color: #94a3b8;
    cursor: pointer;
  }

  .remove-line-btn:hover {
    background: #fef2f2;
    color: #ef4444;
  }

  :global(.dark) .remove-line-btn:hover {
    background: rgb(239 68 68 / 0.12);
    color: #f87171;
  }

  .shared-fields,
  .edit-grid,
  .line-grid {
    display: grid;
    gap: 0.75rem;
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .line-grid .span-2 {
    grid-column: span 2;
  }

  label span {
    display: block;
    margin-bottom: 0.35rem;
    font-size: 0.8125rem;
    font-weight: 500;
    color: #64748b;
  }

  :global(.dark) label span {
    color: #94a3b8;
  }

  input:not([type="checkbox"]),
  select {
    width: 100%;
    box-sizing: border-box;
    min-height: 38px;
    border-radius: 0.5rem;
    border: 1px solid #e6eaed;
    background: white;
    padding: 0.5rem 0.75rem;
    font-size: 0.875rem;
    line-height: 1.25;
    color: inherit;
  }

  input:disabled {
    background: #e2e8f0;
    color: #94a3b8;
    cursor: not-allowed;
    opacity: 0.85;
  }

  :global(.dark) input:disabled {
    background: #1e293b;
    color: #64748b;
    opacity: 0.6;
  }

  select {
    padding-right: 2.25rem;
  }

  :global(.dark) input,
  :global(.dark) select {
    border-color: rgb(255 255 255 / 0.12);
    background: #111827;
  }

  .form-alert {
    margin: 0 1.25rem;
    padding: 0.65rem 0.85rem;
    border-radius: 0.375rem;
    font-size: 0.875rem;
  }

  .form-alert.error {
    background: #fef2f2;
    border: 1px solid #fecaca;
    color: #b91c1c;
  }

  :global(.dark) .form-alert.error {
    background: rgb(239 68 68 / 0.12);
    border-color: rgb(239 68 68 / 0.35);
    color: #fca5a5;
  }

  .modal-body {
    padding: 1rem 1.25rem;
  }

  .modal-body p {
    margin: 0 0 0.5rem;
    font-size: 0.9375rem;
  }

  .detail {
    font-size: 0.8125rem;
    color: #64748b;
  }

  :global(.dark) .detail {
    color: #94a3b8;
  }

  footer {
    display: flex;
    justify-content: flex-end;
    gap: 0.5rem;
    padding: 0.85rem 1.25rem;
    border-top: 1px solid #e6eaed;
  }

  :global(.dark) footer {
    border-top-color: rgb(255 255 255 / 0.1);
  }

  .danger-btn {
    display: inline-flex;
    height: 30px;
    align-items: center;
    justify-content: center;
    border-radius: 5px;
    border: 1px solid #fca5a5;
    background: #ef4444;
    color: white;
    padding: 0 0.85rem;
    font-size: 0.875rem;
    font-weight: 600;
    cursor: pointer;
  }

  .danger-btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .attr-row {
    display: inline-flex;
    align-items: baseline;
    column-gap: 0.35rem;
  }

  .attr-key {
    font-weight: 600;
  }

  .attr-sep {
    opacity: 0.75;
    margin: 0 0.15rem;
  }

  .generated-name-field .generated-name-preview {
    margin: 0.35rem 0 0;
    padding: 0.55rem 0.65rem;
    border-radius: 0.375rem;
    border: 1px solid var(--border, #e5e7eb);
    background: var(--muted, #f9fafb);
    font-size: 0.9rem;
    min-height: 2.25rem;
  }

  .generated-name-placeholder {
    color: #6b7280;
    font-style: italic;
  }

  @media (max-width: 640px) {
    .shared-fields,
    .edit-grid,
    .line-grid,
    .prices-row {
      grid-template-columns: 1fr;
    }

    .line-grid .span-2 {
      grid-column: span 1;
    }
  }
</style>
