import {
	buildCatalogProductName,
	usesAutoGeneratedProductName,
} from '$lib/inventory/productLabel';

export const MAX_UNIT_LENGTH = 64;

export const PRODUCT_TYPE_FIELDS: Record<string, string[]> = {
	glass: ['thickness', 'color', 'figure', 'factor'],
	brake_lining: ['model_number', 'country'],
	coffee_tools: ['name', 'capacity', 'capacity_unit'],
};

export function normalizeProductTypeName(raw: string): string {
	const t = raw.trim();
	if (t === 'brake_pad' || t === 'break_pad') return 'brake_lining';
	return t;
}

export function parseOptionalString(raw: FormDataEntryValue | null): string | null {
	if (raw === null || raw === undefined) return null;
	const s = String(raw).trim();
	return s === '' ? null : s;
}

export function parseUnit(raw: FormDataEntryValue | null): string | null {
	const s = String(raw ?? '').trim();
	if (!s) return null;
	if (s.length > MAX_UNIT_LENGTH) return null;
	return s;
}

export function parseAttributes(raw: FormDataEntryValue | null): Record<string, unknown> {
	if (raw == null) return {};
	const s = String(raw).trim();
	if (!s) return {};
	try {
		const parsed = JSON.parse(s) as unknown;
		if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return {};
		const out: Record<string, unknown> = {};
		for (const [k, v] of Object.entries(parsed as Record<string, unknown>)) {
			if (!k.trim()) continue;
			if (v == null) continue;
			if (typeof v === 'string') {
				const t = v.trim();
				if (!t) continue;
				out[k] = t;
			} else {
				out[k] = v;
			}
		}
		return out;
	} catch {
		return {};
	}
}

export function parseInvestors(raw: FormDataEntryValue | null): string[] {
	try {
		const parsed = JSON.parse(String(raw ?? '[]')) as unknown;
		return Array.isArray(parsed)
			? parsed.filter((id): id is string => typeof id === 'string' && id.trim() !== '')
			: [];
	} catch {
		return [];
	}
}

export function parsePositiveNumber(raw: FormDataEntryValue | null): number {
  const s = String(raw ?? '').trim();
  if (!s) return 0;
  const n = Number(s.replace(/[^0-9.-]/g, ''));
  return Number.isFinite(n) && n >= 0 ? n : 0;
}

export function parsePositiveFactor(
	attributes: Record<string, unknown>,
	explicitFactor: unknown,
): number {
	const fromAttr = attributes.factor;
	if (fromAttr != null) {
		const n = Number(String(fromAttr).replace(/[^0-9.-]/g, ''));
		if (Number.isFinite(n) && n > 0) return n;
	}
	if (explicitFactor != null) {
		const n = Number(String(explicitFactor).replace(/[^0-9.-]/g, ''));
		if (Number.isFinite(n) && n > 0) return n;
	}
	return 1;
}

/** Resolve `products.name` — auto-built from attributes for known types, else explicit name. */
export function resolveCatalogProductName(input: {
	productTypeName: string;
	attributes: Record<string, unknown>;
	explicitName?: string | null;
}): { name: string | null; error: string | null } {
	const typeKey = normalizeProductTypeName(input.productTypeName);

	if (usesAutoGeneratedProductName(typeKey)) {
		const name = buildCatalogProductName(typeKey, input.attributes).trim();
		if (!name || name === 'Stock') {
			const fields = PRODUCT_TYPE_FIELDS[typeKey] ?? [];
			const hint =
				fields.length > 0
					? fields.map((f) => f.replaceAll('_', ' ')).join(', ')
					: 'product attributes';
			return {
				name: null,
				error: `Enter ${hint} so the product name can be generated`,
			};
		}
		return { name, error: null };
	}

	const name = String(input.explicitName ?? '').trim();
	if (!name) return { name: null, error: 'Product name is required' };
	return { name, error: null };
}

export type ReceiveLineInput =
	| {
			mode: 'existing';
			product_id: string;
			quantity: number;
			purchased_price: number;
			selling_price: number;
	  }
	| {
			mode: 'new';
			product_type_id: string;
			product_type_name: string;
			name: string;
			default_unit: string;
			attributes: Record<string, unknown>;
			investors: string[];
			factor: number;
			barcode?: string | null;
			qr_code?: string | null;
			quantity: number;
			purchased_price: number;
			selling_price: number;
	  };

export function parseReceiveLines(raw: string): ReceiveLineInput[] {
	const parsed = JSON.parse(raw) as unknown;
	if (!Array.isArray(parsed) || parsed.length === 0) {
		throw new Error('Add at least one receive line');
	}
	if (parsed.length > 15) throw new Error('Too many lines (max 15)');

	const lines: ReceiveLineInput[] = [];
	for (const item of parsed) {
		if (!item || typeof item !== 'object') throw new Error('Invalid receive line');
		const rec = item as Record<string, unknown>;
		const mode = String(rec.mode ?? '').trim();
		const quantity = Number(rec.quantity);
		const purchased_price = Number(rec.purchased_price);
		const selling_price = Number(rec.selling_price);
		if (!Number.isFinite(quantity) || quantity <= 0) {
			throw new Error('Each line needs quantity greater than zero');
		}
		if (!Number.isFinite(purchased_price) || purchased_price < 0) {
			throw new Error('Each line needs a valid purchase price');
		}
		if (!Number.isFinite(selling_price) || selling_price <= 0) {
			throw new Error('Each line needs a valid selling price');
		}

		if (mode === 'existing') {
			const product_id = String(rec.product_id ?? '').trim();
			if (!product_id) throw new Error('Select a product for each line');
			lines.push({
				mode: 'existing',
				product_id,
				quantity,
				purchased_price,
				selling_price,
			});
		} else if (mode === 'new') {
			const product_type_id = String(rec.product_type_id ?? '').trim();
			const product_type_name = normalizeProductTypeName(String(rec.product_type_name ?? ''));
			const explicitName = String(rec.name ?? '').trim();
			const default_unit = parseUnit(rec.default_unit as string) ?? '';
			const attributes = (rec.attributes ?? {}) as Record<string, unknown>;
			const investors = Array.isArray(rec.investors)
				? rec.investors.filter((id): id is string => typeof id === 'string' && id.trim() !== '')
				: [];
			const factor = parsePositiveFactor(attributes, rec.factor);
			const barcode = parseOptionalString(rec.barcode as FormDataEntryValue | null);
			const qr_code = parseOptionalString(rec.qr_code as FormDataEntryValue | null);
			if (!product_type_id) throw new Error('Product type is required for new products');
			if (!product_type_name) throw new Error('Product type name is required');
			const resolved = resolveCatalogProductName({
				productTypeName: product_type_name,
				attributes,
				explicitName,
			});
			if (resolved.error || !resolved.name) {
				throw new Error(resolved.error ?? 'Product name is required for new products');
			}
			if (!default_unit) throw new Error('Unit is required for new products');
			if (investors.length === 0) throw new Error('Select at least one investor for new products');
			lines.push({
				mode: 'new',
				product_type_id,
				product_type_name,
				name: resolved.name,
				default_unit,
				attributes,
				investors,
				factor,
				barcode,
				qr_code,
				quantity,
				purchased_price,
				selling_price,
			});
		} else {
			throw new Error('Each line must be existing or new product');
		}
	}
	return lines;
}
