import { buildStockDescriptor, buildStockLabel, formatProductTypeLabel } from '$lib/stockLabel';
import type { ProductRecord } from './types';

/** Product types whose `products.name` is built from attributes (legacy stock label rules). */
export const AUTO_NAME_PRODUCT_TYPES = new Set([
	'glass',
	'brake_lining',
	'brake_pad',
	'break_pad',
	'coffee_tools',
]);

export function usesAutoGeneratedProductName(productTypeKey: string): boolean {
	const key = productTypeKey.trim().toLowerCase();
	if (key === 'brake_pad' || key === 'break_pad') return true;
	return AUTO_NAME_PRODUCT_TYPES.has(key);
}

/** Value stored in `products.name` — descriptor only, same as legacy stock naming. */
export function buildCatalogProductName(
	productTypeKey: string,
	attributes: Record<string, unknown> | null | undefined,
): string {
	const typeKey = productTypeKey.trim().toLowerCase();
	return buildStockDescriptor({
		type: typeKey,
		product_type: typeKey,
		attributes: attributes ?? {},
	});
}

export function productTypeKey(product: ProductRecord): string {
	const fromRel = product.product_type?.name;
	if (fromRel != null && String(fromRel).trim() !== '') {
		return String(fromRel).trim().toLowerCase();
	}
	return '';
}

/** Display label for a catalog product row. */
export function buildProductLabel(product: ProductRecord): string {
	const name = String(product.name ?? '').trim();
	if (name) {
		const typeSuffix = formatProductTypeLabel(productTypeKey(product));
		return typeSuffix && typeSuffix !== '—' ? `${name} (${typeSuffix})` : name;
	}
	return buildStockLabel({
		type: productTypeKey(product),
		product_type: productTypeKey(product),
		attributes: product.attributes ?? {},
	});
}
