<script lang="ts">
  import { enhance } from "$app/forms";
  import { goto } from "$app/navigation";
  import { navigating } from "$app/state";
  import { page } from "$app/stores";
  import { Pencil } from "@lucide/svelte";
  import { tick } from "svelte";
  import TableLoading from "$lib/components/TableLoading.svelte";
  import TablePagination from "$lib/components/TablePagination.svelte";
  import TableSearchInput from "$lib/components/TableSearchInput.svelte";
  import { mc } from "$lib/merchant-styles.js";

  import {
    SUBSCRIPTION_BLOCKED_MESSAGE,
    subscriptionBlocksMutations,
  } from "$lib/subscription/client";
  import {
    afterToast,
    showToast,
    toastFromActionResult,
    TOAST_MS,
  } from "$lib/toast";
  import {
    buildCatalogProductName,
    buildProductLabel,
    usesAutoGeneratedProductName,
  } from "$lib/inventory/productLabel";
  import type { PageData } from "./$types";

  type Investor = {
    id: string;
    first_name: string;
    last_name: string;
    phone_number: string;
  };
  type ProductType = { id: string; name?: string | null };
  type Product = {
    id: string;
    name: string;
    displayName: string;
    default_unit: string;
    attributes?: Record<string, unknown> | null;
    investors?: string[] | null;
    is_active?: boolean | null;
    barcode?: string | null;
    qr_code?: string | null;
    product_type?: ProductType | null;
  };

  let { data }: { data: PageData } = $props();

  let products = $state(data.products as Product[]);
  let totalCount = $state((data as { totalCount: number }).totalCount ?? 0);
  let showModal = $state(false);
  let editingProductId = $state<string | null>(null);
  let formPending = $state(false);
  let errorMessage = $state("");

  const subscriptionLocked = $derived($subscriptionBlocksMutations);
  const investors = data.investors as Investor[];
  const productTypes = (data.productTypes ?? []) as ProductType[];
  const PRODUCT_TYPE_FIELDS = (data.productTypeFields ?? {}) as Record<
    string,
    string[]
  >;

  let searchQuery = $state($page.url.searchParams.get("search") ?? "");
  let tablePage = $state(Number($page.url.searchParams.get("page")) || 1);
  let tablePageSize = $state(Number($page.url.searchParams.get("pageSize")) || 10);
  let searchDebounceTimer: ReturnType<typeof setTimeout> | undefined;
  let suppressPageNav = $state(false);

  let productName = $state("");
  let selectedProductTypeId = $state("");
  let selectedProductTypeName = $state("");
  let defaultUnit = $state("");
  let attributes = $state<Record<string, string>>({});
  let barcode = $state("");
  let qrCode = $state("");
  let isActive = $state(true);
  let selectedInvestorIds = $state<string[]>([]);
  let investorDropdownOpen = $state(false);
  let investorMultiselectEl = $state<HTMLDivElement | null>(null);
  let investorMenuPortalEl = $state<HTMLDivElement | null>(null);
  let investorMenuPosStyle = $state("");
  let investorsValidityProxyEl = $state<HTMLInputElement | null>(null);

  $effect(() => {
    products = data.products as Product[];
    totalCount = (data as { totalCount: number }).totalCount ?? 0;
  });

  function typeFromProduct(p: Product): string {
    return String(p.product_type?.name ?? "")
      .trim()
      .toLowerCase();
  }

  function typeDisplay(t: string | null | undefined) {
    const x = String(t ?? "").trim();
    if (!x) return "—";
    if (x === "brake_lining" || x === "brake_pad" || x === "break_pad")
      return "Brake lining";
    return x.replaceAll("_", " ").replace(/\b\w/g, (m) => m.toUpperCase());
  }

  function attributeLabel(key: string): string {
    if (key === "model_number") return "Model No";
    if (key === "capacity_unit") return "Capacity unit";
    return key.replaceAll("_", " ").replace(/\b\w/g, (m) => m.toUpperCase());
  }

  function currentTypeFields(): string[] {
    return PRODUCT_TYPE_FIELDS[selectedProductTypeName] ?? [];
  }

  const usesAutoName = $derived(
    usesAutoGeneratedProductName(selectedProductTypeName),
  );

  const generatedProductName = $derived(
    usesAutoName
      ? buildCatalogProductName(selectedProductTypeName, attributes)
      : productName.trim(),
  );

  const generatedDisplayLabel = $derived.by(() => {
    if (!usesAutoName || !generatedProductName || generatedProductName === "Stock") {
      return "";
    }
    return buildProductLabel({
      id: "",
      name: generatedProductName,
      default_unit: defaultUnit || "—",
      attributes,
      product_type: { id: "", name: selectedProductTypeName },
    });
  });

  function navigateWithState() {
    const params = new URLSearchParams();
    if (searchQuery) params.set("search", searchQuery);
    if (tablePage > 1) params.set("page", String(tablePage));
    if (tablePageSize !== 10) params.set("pageSize", String(tablePageSize));
    const qs = params.toString();
    goto(qs ? `/products?${qs}` : "/products", { replaceState: true, keepFocus: true });
  }

  $effect(() => {
    const q = searchQuery;
    const currentSearch = $page.url.searchParams.get("search") ?? "";
    if (q === currentSearch) return;

    clearTimeout(searchDebounceTimer);
    searchDebounceTimer = setTimeout(() => {
      suppressPageNav = true;
      tablePage = 1;
      navigateWithState();
      suppressPageNav = false;
    }, 600);
  });

  $effect(() => {
    if (suppressPageNav) return;
    const pg = tablePage;
    const ps = tablePageSize;
    const urlPage = Number($page.url.searchParams.get("page")) || 1;
    const urlPageSize = Number($page.url.searchParams.get("pageSize")) || 10;
    if (pg === urlPage && ps === urlPageSize) return;
    navigateWithState();
  });

  function activeLabel(active: boolean | null | undefined): string {
    return active === false ? "Inactive" : "Active";
  }

  function resetForm() {
    productName = "";
    selectedProductTypeId = "";
    selectedProductTypeName = "";
    defaultUnit = "";
    attributes = {};
    barcode = "";
    qrCode = "";
    isActive = true;
    selectedInvestorIds = [];
    investorDropdownOpen = false;
    investorMenuPosStyle = "";
    editingProductId = null;
  }

  function openCreateModal() {
    if (subscriptionLocked) return;
    errorMessage = "";
    resetForm();
    showModal = true;
  }

  function openEditModal(product: Product, event: Event) {
    if (subscriptionLocked) return;
    event.stopPropagation();
    errorMessage = "";
    editingProductId = product.id;
    productName = String(product.name ?? "").trim();
    const typeName = typeFromProduct(product);
    selectedProductTypeId =
      product.product_type?.id ??
      productTypes.find(
        (pt) =>
          String(pt.name ?? "")
            .trim()
            .toLowerCase() === typeName,
      )?.id ??
      "";
    selectedProductTypeName = typeName;
    defaultUnit = String(product.default_unit ?? "").trim();
    attributes = buildAttributesForEdit(product, typeName);
    barcode = String(product.barcode ?? "").trim();
    qrCode = String(product.qr_code ?? "").trim();
    isActive = product.is_active !== false;
    selectedInvestorIds = Array.isArray(product.investors)
      ? [...product.investors]
      : [];
    investorDropdownOpen = false;
    showModal = true;
  }

  function closeModal() {
    if (formPending) return;
    showModal = false;
    resetForm();
  }

  function buildAttributesForEdit(
    product: Product,
    typeKey: string,
  ): Record<string, string> {
    const out: Record<string, string> = {};
    const attrs = product.attributes ?? {};
    if (attrs && typeof attrs === "object" && !Array.isArray(attrs)) {
      for (const [k, v] of Object.entries(attrs)) {
        if (!k.trim() || v == null || v === "") continue;
        out[k] = String(v).trim();
      }
    }
    for (const key of PRODUCT_TYPE_FIELDS[typeKey] ?? []) {
      if (out[key] == null) out[key] = "";
    }
    return out;
  }

  function toggleInvestor(id: string) {
    if (selectedInvestorIds.includes(id)) {
      selectedInvestorIds = selectedInvestorIds.filter((x) => x !== id);
    } else {
      selectedInvestorIds = [...selectedInvestorIds, id];
    }
    investorDropdownOpen = false;
  }

  function investorLabel(ids: string[]) {
    if (ids.length === 0) return "Select investors";
    const names = investors
      .filter((i) => ids.includes(i.id))
      .map((i) => `${i.first_name} ${i.last_name}`);
    return names.join(", ");
  }

  $effect(() => {
    if (!showModal || !investorsValidityProxyEl) return;
    const el = investorsValidityProxyEl;
    const n = selectedInvestorIds.length;
    if (investors.length === 0) {
      el.setCustomValidity(
        "Add at least one investor to your company before creating a product.",
      );
    } else if (n === 0) {
      el.setCustomValidity("Please select at least one investor.");
    } else {
      el.setCustomValidity("");
    }
  });

  $effect(() => {
    if (!investorDropdownOpen) investorMenuPosStyle = "";
  });

  function updateInvestorMenuPosition() {
    const el = investorMultiselectEl;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    const gap = 6;
    const pad = 10;
    const width = rect.width;
    let left = Math.max(
      pad,
      Math.min(rect.left, window.innerWidth - width - pad),
    );
    const spaceBelow = window.innerHeight - rect.bottom - gap - pad;
    const spaceAbove = rect.top - gap - pad;
    let top = rect.bottom + gap;
    let maxHeight = Math.min(280, Math.max(100, spaceBelow));
    if (spaceBelow < 120 && spaceAbove > spaceBelow) {
      maxHeight = Math.min(280, Math.max(100, spaceAbove));
      top = rect.top - gap - maxHeight;
      top = Math.max(pad, top);
    }
    investorMenuPosStyle = `top:${top}px;left:${left}px;width:${width}px;max-height:${maxHeight}px`;
  }

  $effect(() => {
    if (!investorDropdownOpen || !showModal) return;

    let raf = 0;
    const schedulePosition = () => {
      cancelAnimationFrame(raf);
      raf = requestAnimationFrame(() => updateInvestorMenuPosition());
    };

    void tick().then(schedulePosition);

    window.addEventListener("resize", schedulePosition);
    window.addEventListener("scroll", schedulePosition, true);

    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("resize", schedulePosition);
      window.removeEventListener("scroll", schedulePosition, true);
    };
  });

  $effect(() => {
    if (!showModal || formPending || !investorDropdownOpen) return;

    const onPointerDown = (e: PointerEvent) => {
      const node = e.target as Node;
      if (
        !investorMultiselectEl?.contains(node) &&
        !investorMenuPortalEl?.contains(node)
      ) {
        investorDropdownOpen = false;
      }
    };

    document.addEventListener("pointerdown", onPointerDown, true);
    return () =>
      document.removeEventListener("pointerdown", onPointerDown, true);
  });
</script>

<section class={mc.pageHeader}>
  <div>
    <h1 class={mc.pageTitle}>Products</h1>
    <p class={mc.pageSubtitle}>
      Company product catalog. Click a row to view stock movements.
    </p>
  </div>
  <button
    type="button"
    class={mc.primaryBtn}
    onclick={openCreateModal}
    disabled={subscriptionLocked}
    title={subscriptionLocked ? SUBSCRIPTION_BLOCKED_MESSAGE : undefined}
  >
    Create Product
  </button>
</section>

{#if !data.companyId}
  <p class="mb-4 text-sm text-red-700 dark:text-red-300">
    Your branch has no company linked, so products cannot be loaded.
  </p>
{/if}

{#if errorMessage && !showModal}
  <div class={mc.alertError}>
    <p>{errorMessage}</p>
  </div>
{/if}

{#if showModal}
  <div
    class="modal-overlay"
    role="button"
    tabindex="0"
    onclick={() => !formPending && closeModal()}
    onkeydown={(e) =>
      !formPending && (e.key === "Enter" || e.key === " ") && closeModal()}
  ></div>
  <dialog
    open
    class="modal"
    onclick={(e) => e.stopPropagation()}
    oncancel={(e) => formPending && e.preventDefault()}
  >
    <header>
      <h2>{editingProductId ? "Edit Product" : "Create Product"}</h2>
      <button
        class="icon"
        aria-label="Close"
        disabled={formPending}
        onclick={closeModal}>✕</button
      >
    </header>
    <form
      class="form product-form"
      method="POST"
      action={editingProductId ? "?/updateProduct" : "?/createProduct"}
      use:enhance={({ formElement, cancel }) => {
        if (!formElement.reportValidity()) {
          cancel();
          return;
        }
        formPending = true;
        return async ({ update, result }) => {
          try {
            await update();
          } finally {
            formPending = false;
          }
          const t = toastFromActionResult(result);
          if (t) showToast(t.message, t.variant);
          const ok =
            result.type === "success" &&
            result.data &&
            typeof result.data === "object" &&
            "success" in result.data &&
            (result.data as { success?: boolean }).success === true;
          if (ok) {
            errorMessage = "";
            showModal = false;
            resetForm();
            afterToast(TOAST_MS, () => window.location.reload());
          } else if (t?.variant === "error") {
            errorMessage = t.message;
          }
        };
      }}
    >
      {#if errorMessage}
        <div class="modal-form-alert error" role="alert">
          <p>{errorMessage}</p>
        </div>
      {/if}
      {#if editingProductId}
        <input type="hidden" name="id" value={editingProductId} />
        <input type="hidden" name="is_active" value={isActive ? "true" : "false"} />
      {/if}
      <input
        type="hidden"
        name="product_type_name"
        value={selectedProductTypeName}
      />
      <input type="hidden" name="attributes" value={JSON.stringify(attributes)} />
      <fieldset class="product-form-fields" disabled={formPending}>
        <div class="grid">
          {#if !usesAutoName}
            <label>
              <span>Name</span>
              <input type="text" name="name" bind:value={productName} required />
            </label>
          {/if}
          <label>
            <span>Product type</span>
            <select
              name="product_type"
              bind:value={selectedProductTypeId}
              required
              class="native-select"
              onchange={() => {
                const found = productTypes.find(
                  (p) => p.id === selectedProductTypeId,
                );
                selectedProductTypeName = String(found?.name ?? "")
                  .trim()
                  .toLowerCase();
                if (!editingProductId) {
                  attributes = {};
                } else {
                  const keys = PRODUCT_TYPE_FIELDS[selectedProductTypeName] ?? [];
                  const next: Record<string, string> = {};
                  for (const k of keys) {
                    next[k] = attributes[k] ?? "";
                  }
                  attributes = next;
                }
              }}
            >
              <option value="">Select product type</option>
              {#each productTypes as pt}
                <option value={pt.id}>{typeDisplay(pt.name ?? "")}</option>
              {/each}
            </select>
          </label>
          <label>
            <span>Default unit</span>
            <input
              type="text"
              name="default_unit"
              bind:value={defaultUnit}
              required
              maxlength="64"
              autocomplete="off"
              placeholder="Pieces, Set, kg…"
            />
          </label>
          <div class="field">
            <span
              >Investors <span class="req-mark" aria-hidden="true">*</span></span
            >
            <input
              bind:this={investorsValidityProxyEl}
              type="text"
              class="validity-proxy"
              tabindex="-1"
              autocomplete="off"
              aria-hidden="true"
              value={selectedInvestorIds.length > 0 ? "x" : ""}
              required
            />
            <input
              type="hidden"
              name="investors"
              value={JSON.stringify(selectedInvestorIds)}
            />
            {#if investors.length > 0}
              <div class="multiselect" bind:this={investorMultiselectEl}>
                <button
                  type="button"
                  class="select-trigger"
                  onclick={() => (investorDropdownOpen = !investorDropdownOpen)}
                >
                  {investorLabel(selectedInvestorIds)}
                </button>
              </div>
            {/if}
          </div>
          {#each currentTypeFields() as fieldName}
            <label>
              <span>{attributeLabel(fieldName)}</span>
              <input type="text" bind:value={attributes[fieldName]} />
            </label>
          {/each}
          {#if usesAutoName}
            <div class="field span-2 generated-name-field">
              <span>Product name</span>
              <p class="generated-name-preview" aria-live="polite">
                {#if generatedDisplayLabel}
                  {generatedDisplayLabel}
                {:else}
                  <span class="generated-name-placeholder"
                    >Fill in the attributes above — name is built automatically.</span
                  >
                {/if}
              </p>
              <input type="hidden" name="name" value={generatedProductName === "Stock" ? "" : generatedProductName} />
            </div>
          {/if}
          <label>
            <span>Barcode <span class="optional">(optional)</span></span>
            <input type="text" name="barcode" bind:value={barcode} />
          </label>
          <label>
            <span>QR code <span class="optional">(optional)</span></span>
            <input type="text" name="qr_code" bind:value={qrCode} />
          </label>
          {#if editingProductId}
            <label class="checkbox-field">
              <input type="checkbox" bind:checked={isActive} />
              <span>Active</span>
            </label>
          {/if}
        </div>
      </fieldset>
      <footer>
        <button
          type="button"
          class="ghost"
          onclick={closeModal}
          disabled={formPending}>Cancel</button
        >
        <button type="submit" class="primary" disabled={formPending}>
          {formPending
            ? editingProductId
              ? "Updating…"
              : "Creating…"
            : editingProductId
              ? "Update"
              : "Create"}
        </button>
      </footer>
    </form>
  </dialog>
  {#if investorDropdownOpen && investors.length > 0 && investorMenuPosStyle !== ""}
    <div
      bind:this={investorMenuPortalEl}
      class="select-menu investor-menu-portal"
      style={investorMenuPosStyle}
    >
      {#each investors as inv}
        <label class="option">
          <input
            type="checkbox"
            checked={selectedInvestorIds.includes(inv.id)}
            onchange={() => toggleInvestor(inv.id)}
          />
          <span>{inv.first_name} {inv.last_name}</span>
        </label>
      {/each}
    </div>
  {/if}
{/if}

<section class={mc.tableSection}>
  <div class={mc.tableToolbar}>
    <TableSearchInput
      bind:value={searchQuery}
      placeholder="Search by name, type, unit…"
      ariaLabel="Search products"
      class="flex-1"
    />
  </div>
  <div class="overflow-x-auto">
    <table class={mc.table}>
      <thead>
        <tr>
          <th class={mc.colNumHead}>#</th>
          <th class={mc.th}>Name</th>
          <th class={mc.th}>Type</th>
          <th class={mc.th}>Unit</th>
          <th class={mc.th}>Status</th>
          <th class={mc.thCenter}>Actions</th>
        </tr>
      </thead>
      <tbody>
        {#if navigating.to}
          <TableLoading rows={5} cols={6} />
        {:else}
          {#each products as p, i}
            <tr
              class={mc.rowClickable}
              onclick={() => goto(`/products/${p.id}`)}
              tabindex="0"
              role="button"
            >
              <td class={mc.colNum}>{(tablePage - 1) * tablePageSize + i + 1}</td>
              <td class={mc.td}>{p.displayName || p.name || "—"}</td>
              <td class={mc.td}>{typeDisplay(typeFromProduct(p))}</td>
              <td class={mc.td}>{p.default_unit || "—"}</td>
              <td class={mc.td}>
                <span
                  class="status-pill"
                  class:status-inactive={p.is_active === false}
                >
                  {activeLabel(p.is_active)}
                </span>
              </td>
              <td class={mc.tdCenter}>
                <button
                  type="button"
                  class={mc.actionBtn}
                  onclick={(e) => openEditModal(p, e)}
                  disabled={subscriptionLocked}
                  aria-label="Edit product"
                  title={subscriptionLocked
                    ? SUBSCRIPTION_BLOCKED_MESSAGE
                    : "Edit product"}
                >
                  <Pencil size={14} strokeWidth={2} />
                </button>
              </td>
            </tr>
          {/each}
          {#if products.length === 0}
            <tr>
              <td colspan="6" class={mc.emptyCell}>
                {#if searchQuery.trim()}
                  No products match your search.
                {:else}
                  No products found. Create your first product to get started.
                {/if}
              </td>
            </tr>
          {/if}
        {/if}
      </tbody>
    </table>
  </div>
  <TablePagination
    bind:page={tablePage}
    bind:pageSize={tablePageSize}
    total={totalCount}
  />
</section>

<style>
  fieldset.product-form-fields {
    border: none;
    padding: 0;
    margin: 0;
    min-width: 0;
  }

  input.validity-proxy {
    position: absolute;
    width: 1px;
    height: 1px;
    margin: -1px;
    padding: 0;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    clip-path: inset(50%);
    white-space: nowrap;
    border: 0;
    opacity: 0;
    pointer-events: none;
  }

  .field {
    position: relative;
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
  }

  .multiselect {
    position: relative;
  }

  .req-mark {
    color: #f97373;
    font-weight: 700;
  }

  .generated-name-field .generated-name-preview {
    margin: 0;
    padding: 0.55rem 0.65rem;
    border-radius: 0.375rem;
    border: 1px solid var(--border, #e5e7eb);
    background: var(--muted, #f9fafb);
    font-size: 0.9rem;
    min-height: 2.25rem;
  }

  .generated-name-placeholder {
    color: #6b7280;
    font-style: italic;
  }

  .optional {
    font-weight: 400;
    opacity: 0.75;
  }

  .checkbox-field {
    flex-direction: row;
    align-items: center;
    gap: 0.5rem;
  }

  .checkbox-field input[type="checkbox"] {
    width: auto;
  }

  .status-pill {
    display: inline-flex;
    align-items: center;
    border-radius: 9999px;
    padding: 0.125rem 0.5rem;
    font-size: 0.75rem;
    font-weight: 600;
    background: color-mix(in oklab, #67b186, transparent 75%);
    color: #166534;
  }

  .status-pill.status-inactive {
    background: color-mix(in oklab, #9ca3af, transparent 70%);
    color: #374151;
  }

  :global(html.dark) .status-pill {
    color: #bbf7d0;
  }

  :global(html.dark) .status-pill.status-inactive {
    color: #d1d5db;
  }
</style>
